CREATE OR REFRESH MATERIALIZED VIEW planogram_slots
COMMENT 'Synthetic shelf facings, placement, promotion, and margin data by Paris store'
AS
SELECT *
FROM VALUES
  ('FR-PAR-001', 1, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'eye'),
  ('FR-PAR-001', 1, 2, 'Yoplait Skyr Nature', 'Yoplait', 'Yoplait', FALSE, 0.22, 'eye'),
  ('FR-PAR-001', 1, 3, 'Oikos High Protein Strawberry', 'Danone', 'Oikos', TRUE, 0.40, 'eye'),
  ('FR-PAR-001', 1, 4, 'Nestlé Ski Vanille', 'Nestlé', 'Ski', FALSE, 0.15, 'eye'),
  ('FR-PAR-001', 2, 1, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'mid'),
  ('FR-PAR-001', 2, 2, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'mid'),
  ('FR-PAR-001', 2, 3, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'mid'),
  ('FR-PAR-001', 2, 4, 'Activia Fruits Mix', 'Danone', 'Activia', TRUE, 0.26, 'mid'),
  ('FR-PAR-001', 3, 1, 'Volvic Touch of Fruit', 'Danone', 'Volvic', FALSE, 0.18, 'low'),
  ('FR-PAR-001', 3, 2, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'low'),
  ('FR-PAR-001', 3, 3, 'Oikos Triple Zero', 'Danone', 'Oikos', TRUE, 0.38, 'low'),
  ('FR-PAR-001', 3, 4, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'low'),
  ('FR-PAR-002', 1, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'eye'),
  ('FR-PAR-002', 1, 2, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'eye'),
  ('FR-PAR-002', 1, 3, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'eye'),
  ('FR-PAR-002', 2, 1, 'Yoplait Skyr Nature', 'Yoplait', 'Yoplait', FALSE, 0.22, 'mid'),
  ('FR-PAR-003', 1, 1, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'eye'),
  ('FR-PAR-003', 1, 2, 'Activia Fruits Mix', 'Danone', 'Activia', TRUE, 0.26, 'eye'),
  ('FR-PAR-003', 1, 3, 'Yoplait Skyr Nature', 'Yoplait', 'Yoplait', FALSE, 0.22, 'eye'),
  ('FR-PAR-003', 2, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'mid'),
  ('FR-PAR-003', 2, 2, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'mid'),
  ('FR-PAR-004', 1, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'eye'),
  ('FR-PAR-004', 1, 2, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'eye'),
  ('FR-PAR-004', 1, 3, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'eye'),
  ('FR-PAR-005', 1, 1, 'Yoplait Skyr Nature', 'Yoplait', 'Yoplait', FALSE, 0.22, 'eye'),
  ('FR-PAR-005', 1, 2, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'eye'),
  ('FR-PAR-005', 1, 3, 'Nestlé Ski Vanille', 'Nestlé', 'Ski', FALSE, 0.15, 'eye'),
  ('FR-PAR-005', 1, 4, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'eye'),
  ('FR-PAR-005', 2, 1, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'mid'),
  ('FR-PAR-005', 2, 2, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'mid'),
  ('FR-PAR-005', 2, 3, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'mid'),
  ('FR-PAR-005', 2, 4, 'Empty / OOS', 'Empty', '—', FALSE, 0.00, 'mid'),
  ('FR-PAR-005', 3, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'low'),
  ('FR-PAR-005', 3, 2, 'Oikos High Protein Strawberry', 'Danone', 'Oikos', TRUE, 0.40, 'low'),
  ('FR-PAR-006', 1, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'eye'),
  ('FR-PAR-006', 1, 2, 'Nestlé Ski Vanille', 'Nestlé', 'Ski', FALSE, 0.15, 'eye'),
  ('FR-PAR-006', 1, 3, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'eye'),
  ('FR-PAR-007', 1, 1, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'eye'),
  ('FR-PAR-007', 1, 2, 'Yoplait Skyr Nature', 'Yoplait', 'Yoplait', FALSE, 0.22, 'eye'),
  ('FR-PAR-007', 1, 3, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'eye'),
  ('FR-PAR-007', 2, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'mid'),
  ('FR-PAR-007', 2, 2, 'Oikos High Protein Strawberry', 'Danone', 'Oikos', TRUE, 0.40, 'mid'),
  ('FR-PAR-007', 2, 3, 'Nestlé Ski Vanille', 'Nestlé', 'Ski', FALSE, 0.15, 'mid'),
  ('FR-PAR-007', 3, 1, 'Oikos Triple Zero', 'Danone', 'Oikos', TRUE, 0.38, 'low'),
  ('FR-PAR-007', 3, 2, 'Activia Fruits Mix', 'Danone', 'Activia', TRUE, 0.26, 'low'),
  ('FR-PAR-008', 1, 1, 'Oikos High Protein Natural 0%', 'Danone', 'Oikos', TRUE, 0.42, 'eye'),
  ('FR-PAR-008', 1, 2, 'Activia Nature', 'Danone', 'Activia', TRUE, 0.28, 'eye'),
  ('FR-PAR-008', 1, 3, 'Actimel Original', 'Danone', 'Actimel', TRUE, 0.31, 'eye')
AS slots(
  store_id,
  shelf_row,
  shelf_col,
  sku_name,
  manufacturer,
  brand,
  promo_tag_required,
  margin_eur,
  shelf_zone
);
