// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    brand_sales_france: {
        name: "brand_sales_france";
        parameters: Record<string, never>;
        result: Array<{
          /** Brand name (Evian, Volvic, Alpro, Activia, etc.) */
          brand: string;
          /** @sqlType DOUBLE */
          value_sales_k_eur: number;
          /** @sqlType DOUBLE */
          incremental_value_k_eur: number;
        }>;
      };
    external_signals: {
        name: "external_signals";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          signal_id: string;
          /** @sqlType STRING */
          store_id: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          source_name: string;
          /** @sqlType STRING */
          signal_type: string;
          /** @sqlType STRING */
          signal_summary: string;
          /** @sqlType STRING */
          valid_from: string;
          /** @sqlType STRING */
          valid_to: string;
          /** @sqlType INT */
          signal_score: number;
          /** @sqlType STRING */
          demand_theme: string;
          /** @sqlType STRING */
          recommended_action: string;
          /** @sqlType STRING */
          expected_impact: string;
          /** @sqlType STRING */
          urgency: string;
        }>;
      };
    lift_assumptions: {
        name: "lift_assumptions";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          strategy_code: string;
          /** @sqlType STRING */
          strategy_label: string;
          /** @sqlType DECIMAL(6,1) */
          estimated_lift_pct: number;
        }>;
      };
    manufacturer_value_share: {
        name: "manufacturer_value_share";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          period_short: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          manufacturer: string;
          /** @sqlType DOUBLE */
          value_sales_k_eur: number;
          /** @sqlType DOUBLE */
          value_share_pct: number;
        }>;
      };
    planogram_by_store: {
        name: "planogram_by_store";
        parameters: {
          /** STRING - use sql.string() */
          store_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          store_id: string;
          /** @sqlType INT */
          shelf_row: number;
          /** @sqlType INT */
          shelf_col: number;
          /** @sqlType STRING */
          sku_name: string;
          /** @sqlType STRING */
          manufacturer: string;
          /** @sqlType STRING */
          brand: string;
          /** @sqlType BOOLEAN */
          promo_tag_required: boolean;
          /** @sqlType DECIMAL(2,2) */
          margin_eur: number;
          /** @sqlType STRING */
          shelf_zone: string;
        }>;
      };
    sos_by_store: {
        name: "sos_by_store";
        parameters: {
          /** STRING - use sql.string() */
          store_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          segment: string;
          /** @sqlType BIGINT */
          facings: number;
          /** @sqlType DECIMAL(26,1) */
          share_pct: number;
        }>;
      };
    store_detail: {
        name: "store_detail";
        parameters: {
          /** STRING - use sql.string() */
          store_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          store_id: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          format: string;
          /** @sqlType STRING */
          retailer: string;
          /** @sqlType DECIMAL(6,4) */
          lat: number;
          /** @sqlType DECIMAL(5,4) */
          lng: number;
          /** @sqlType INT */
          priority_score: number;
          /** @sqlType STRING */
          priority_tier: string;
          /** @sqlType STRING */
          situation_summary: string;
          /** @sqlType DECIMAL(2,2) */
          danone_sos_pct: number;
          /** @sqlType INT */
          compliance_pct: number;
          /** @sqlType INT */
          weekly_sales_eur: number;
        }>;
      };
    store_signals: {
        name: "store_signals";
        parameters: {
          /** STRING - use sql.string() */
          store_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          signal_id: string;
          /** @sqlType STRING */
          store_id: string;
          /** @sqlType STRING */
          source_name: string;
          /** @sqlType STRING */
          signal_type: string;
          /** @sqlType STRING */
          signal_summary: string;
          /** @sqlType STRING */
          valid_from: string;
          /** @sqlType STRING */
          valid_to: string;
          /** @sqlType INT */
          signal_score: number;
          /** @sqlType STRING */
          demand_theme: string;
          /** @sqlType STRING */
          recommended_action: string;
          /** @sqlType STRING */
          expected_impact: string;
          /** @sqlType STRING */
          urgency: string;
        }>;
      };
    stores: {
        name: "stores";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          store_id: string;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          format: string;
          /** @sqlType STRING */
          retailer: string;
          /** @sqlType DECIMAL(6,4) */
          lat: number;
          /** @sqlType DECIMAL(5,4) */
          lng: number;
          /** @sqlType INT */
          priority_score: number;
          /** @sqlType STRING */
          priority_tier: string;
          /** @sqlType STRING */
          situation_summary: string;
          /** @sqlType DECIMAL(2,2) */
          danone_sos_pct: number;
          /** @sqlType INT */
          compliance_pct: number;
          /** @sqlType INT */
          weekly_sales_eur: number;
        }>;
      };
  }
}
